---
title: 'Project: Data Wrangling Exercise 1: Basic Data Manipulation'
author: "Caitlin Davies"
date: "11/11/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Install stringr

library("dplyr")
library("tidyr")
library("stringr")

## Load the Data in RStudio

refine_original <- read.csv("refine_original.csv", header = TRUE, stringsAsFactors = FALSE)

## Clean Up Brand Names

refine_original$company <- sapply(refine_original$company, tolower)

refine_original$company <- str_replace(refine_original$company, "phl", "phil")
refine_original$company <- str_replace(refine_original$company, "lps", "lips")
refine_original$company <- str_replace(refine_original$company, "fil", "phil")
refine_original$company <- str_replace(refine_original$company, "illi", "ili")

refine_original$company <- str_replace(refine_original$company, "0", "o")
refine_original$company <- str_replace(refine_original$company, "ak ", "ak")

refine_original$company <- str_replace(refine_original$company, "lver", "lever")

refine_original <- refine_original[order(refine_original$company),]

## Separate Product Code and Number

refine_original <- refine_original %>%
  separate(Product.code...number, c("product_code", "product_number"), "-")

## Add Product Categories

index <- c("p", "v", "x", "q")
Product_Categories <- c("Smartphone", "TV", "Laptop", "Tablet")

refine_original$product_categories <- Product_Categories[match(refine_original$product_code, index)]

rm(index)
rm(Product_Categories)

## Add Full Address for Geocoding

refine_original <- unite(refine_original, "full_address", address, city, country, sep = ",", remove = FALSE)

## Create Dummy Variables for Company

refine_original$company_philips <- as.numeric(refine_original$company == "philips")
refine_original$company_akzo <- as.numeric(refine_original$company == "akzo")
refine_original$company_van_houten <- as.numeric(refine_original$company == "van houten")
refine_original$company_unilever <- as.numeric(refine_original$company == "unilever")

## Create Dummy Variables for Product Category

refine_original$product_smartphone <- as.numeric(refine_original$product_categories == "Smartphone")
refine_original$product_tv <- as.numeric(refine_original$product_categories == "TV")
refine_original$product_laptop <- as.numeric(refine_original$product_categories == "Laptop")
refine_original$product_tablet <- as.numeric(refine_original$product_categories == "Tablet")

```